- hosts: docker_host
  gather_facts: no

  tasks:
    - docker_container:
        name: java-hello
        image: na3150/java-hello
        state: started
        recreate: yes
        ports:
          - "8080:8080"