- hosts: ansible_host
  gather_facts: no

  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: na3150
        password: "{{ lookup('env', 'TOKEN') }}"
        reauthorize: yes

    - name: Build and Push Image
      docker_image:
        build:
          path: /home/vagrant/java-hello-world
        name: name/java-hello
        push: yes
        source: build